### ISSUE TITLE
ActionController behind TabBar on iOS < 11

### ISSUE THREAD

**Issue by phillippbertram** [CooperRS/RMActionController#40]
Hi,

thanks for providing this control. It really makes building custom action sheets simple. Unfortunately I ran into a problem. If I am using a UITabBarController the action controller is presented **behind** the tab bar on the bottom.

This problem only occurs on devices lower than iOS 11 as you can see in the screenshot.

![tabbar_issue](https://user-images.githubusercontent.com/5442315/30970341-35f2e946-a465-11e7-92ff-b04e10f68ecd.png)

Thanks a lot an kind regards,

Phillipp

**Comment by CooperRS** [comment]
Hi there!

> thanks for providing this control. It really makes building custom action sheets simple.

Thanks! 🙂 

> If I am using a UITabBarController the action controller is presented behind the tab bar on the bottom.

This probably can be solved with the view controller that is used for presenter `RMActionController`. Instead of the following:

```objc
[self presentViewController: animated: completion:]
```

you could try

```objc
[self.tabBarController presentViewController: animated: completion:]
```

The reason why it works in iOS 11 is that `RMActionController` respects the `safeAreaGuide` for aligning the bottom of the view. The `safeAreaGuide` excludes the area where the bottom bar is and `RMActionController` is presented correctly. 

Best regards,
Roland

**Comment by phillippbertram** [comment]
Thanks for the fast reply, that will solve my problem.
