### ISSUE TITLE
Why No Such Module in iOS 12 deployment

### ISSUE THREAD

**Issue by vanillasky771** [CooperRS/RMActionController#48]
No such module 'RMActionController' in Swift

**Comment by CooperRS** [comment]
Hi there! 👋

Can you provide some more details about your isue? For instance, are you using RMActionController because it’s a dependency of RMDateSelectionViewController/RMPickerViewController?

In either case, I. Would guess that it’s a problem with git submodules not being checked out (`git submodule update —init —recursive` would be the command here).

Best regards,
Roland

**Comment by vanillasky771** [comment]
I’m just want to use customActionController in there can I ? 
The pod is already in the framework file

**Comment by CooperRS** [comment]
I assume you want to use the `CustomViewActionController` from this project, right? In order to do so you copied the code from `CustomViewActionController.swift` to your project and added the `RMActionController` pod in your `Podfile`?

If yes, CocoaPods needs to import pods as frameworks instead of static libraries. This makes sure that there is a module for each imported pod (and also a module for the `RMActionController` pod). All you need to do is adding `use_frameworks!` to your `Podfile`. For instance:

```
platform :ios, '8.0'
use_frameworks!

pod "RMActionController", "~> 1.3.1"
```
