### ISSUE TITLE
Doesn't work in iOS 7 + fix

### ISSUE THREAD

**Issue by lorenzoPrimi** [CooperRS/RMActionController#6]
Crashes in iOS 7.1 with message: dyld: Symbol not found: _UIAccessibilityIsReduceMotionEnabled

Suggested fix (if there is a better fix let me know, I can submit a Pull request)
- (BOOL)disableBouncingEffects {
    if ([[[UIDevice currentDevice] systemVersion] floatValue] >= 8.0) {
        if(&UIAccessibilityIsReduceMotionEnabled && UIAccessibilityIsReduceMotionEnabled()) {
            return YES;
        }
    }
    return _disableBouncingEffects;
}

- (BOOL)disableMotionEffects {
    if ([[[UIDevice currentDevice] systemVersion] floatValue] >= 8.0) {
        if(&UIAccessibilityIsReduceMotionEnabled && UIAccessibilityIsReduceMotionEnabled()) {
            return YES;
        }
    }
    return _disableMotionEffects;
}

**Comment by CooperRS** [comment]
Hi,

thanks for your report and the fix :)

But RMActionController uses custom transitions which are totally broken on iOS 7 in landscape mode and only fixed in iOS 8 and above. For this reason RMActionController is only supported for iOS 8 and above and every version of iOS 8 includes UIAccessibilityIsReduceMotionEnabled(). Thus, I think there is no need to change something in the main repository. But the fix may be useful for everyone who uses RMActionController on iOS 7 with portrait mode only apps

**Comment by lorenzoPrimi** [comment]
Exactly my case!
iOS 7+ app portrait only
